spring.application.name=parental-benefit-calculator

spring.datasource.url=jdbc:sqlite:data/benefits.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false